db:
    host: 202.115.44.140
    port: 1521
    user: dangban
    password: 85418825
    db_name: ntci
    db_type: oracle

redis_db:
    host: 127.0.0.1
    port: 6379
    db_name: 0

# 如果微博账号比较多，也可以考虑使用数据库进行读取和修改(比如标记账号的有效性)
weibo_account:
    - account:
        name: w796246076@sina.com
        password: rookiefly
    - account:
        name: 15708437303
        password: rookiefly
    - account:
        name: 18708103033@163.com
        password: rookiefly
    - account:
        name: rookiefly@aliyun.com
        password: rookiefly