db:
    host: 1.1.1.1
    port: 1521
    user: xx
    password: xx
    db_name: xx
    db_type: oracle

redis_db:
    host: 127.0.0.1
    port: 6379
    db_name: 0

# 如果微博账号比较多，也可以考虑使用数据库进行读取和修改(比如标记账号的有效性)
weibo_account:
    - account:
        name: test
        password: yourpassword
