# coding:utf-8
time_out: 200   # 设置抓取和存储一个用户资料超时时间
min_crawl_interal: 4 # 页面请求最小间隔
max_crawl_interal: 7 # 页面请求最大间隔
excp_interal: 5*60 # 请求异常的时候睡眠的时间
max_page: 30  # 转发信息最多抓取多少页
max_retries: 5 # 抓取失败重试次数


db:
    host: 223.129.0.190
    port: 3306
    user: root
    password: 123456
    db_name: weibo
    db_type: mysql

# 保存登录的cookies
redis:
    host: 223.129.0.190
    port: 6379
    password: ''
    cookies: 1
    urls: 2

# celery调度的blocker和backend
brocker: redis://223.129.0.190/5
backend: redis://223.129.0.190/6



