db:
    host: ****
    port: 1521
    user: ****
    password: ****
    db_name: ****
    db_type: oracle

# 如果微博账号比较多，也可以考虑使用数据库进行读取和修改(比如标记账号的有效性)
weibo_account:
    - account:
        name: ****
        password: ****
    - account:
        name: ****
        password: ****
    
